name: Lint Check

on:
  push:

jobs:
  check-formatting:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: yarn install
      - name: Check code with ESLint
        run: yarn lint